### ISSUE TITLE
Wiki-as-a-website is the default and cannot be changed

### ISSUE THREAD

**Issue by AlJohnson** [OSAS/strapping-mediawiki#8]
MediaWiki 1.20.2

Does not allow anonymous editing of wiki.  Omitting $wgGroupPermissions['*']['edit'] = false; does not work.  Also, setting to 'true' does not work either.

**Comment by garrett** [comment]
I have merged in some pending pull requests and cannot recreate this bug.

In my MediaWiki instance, this displays edit links:

``` php
$wgGroupPermissions['*']['edit'] = true;
```

…and this hides edit links (for signed out users):

``` php
$wgGroupPermissions['*']['edit'] = false;
```

I did see that higher in the `LocalSettings.php` file, it was specified before, so it's important that it's near the end of the configurations (or if a line like the above exists already, that it's changed instead).

Please reopen this bug if the latest version is still not working for you. Thanks!

**Comment by AlJohnson** [comment]
Hi Garrett, I just checked this out and I still have the same problem.  You can see it here: http://ec2-50-112-91-143.us-west-2.compute.amazonaws.com/wiki/index.php/Main_Page

There are no other permissions like above specified.  The link above is a fresh wiki install with only fresh SemanticBundle installed.

I don't see how to reopen this issue.  Do I just recreate it?

**Comment by garrett** [comment]
I just reopened the issue.

I do see edit links... but I just realized you probably mean editing the page itself, which means we need to change the check for the top bar in the code. It's an oversight, and I'll look into it.

**Comment by garrett** [comment]
In `LocalSettings.php`, you can add

``` php
$wgStrappingSkinAnonNavbar = true;
```

And the toolbar will show up. (It is already supported in your checkout, by-the-way.)

The two issues that remain:
1. Documentation
2. Adding a sign-in link to the user area

I'll take care of this today, after lunch. :pizza: :coffee:

**Comment by garrett** [comment]
It might be good to change the behavior to just use one variable and consider defaults. 

That is, if anonymous editing is on by default, then editing the entire page makes sense → therefore, the top bar should be on too.

And then we might even want to default to everyone-edits-the-page and have a lockdown mode for wiki-as-a-website. (Basically, swap the default mode.)

**Comment by waldyrious** [comment]
> And then we might even want to default to everyone-edits-the-page and have a lockdown mode for wiki-as-a-website. (Basically, swap the default mode.)

I think that would be great. As long as the readme has simple and clear instructions on how to change the default, this shouldn't harm either usage patterns, while encouraging openness :)

**Comment by garrett** [comment]
In git commit d57221a6a60926d7d899dc49e35bf9bb5926b045, I've added a check to see if editing is available to all, and if so, show the toolbar.

Basically, it checks to see if `$wgGroupPermissions['*']['edit']` is true in addition to other checks.

This reflects what the documentation already states. (Sorry for the confusion before.)

**Comment by garrett** [comment]
`$wgStrappingSkinAnonNavbar` is no longer needed, except in the case you want to disable editing, yet still show the top bar.

Next step: to add a sign-in link in the non-signed-in toolbar.

**Comment by AlJohnson** [comment]
Just wanted to report back that the fixes so far have this skin working well and congrats on a cool new skin for wikis :100:

**Comment by garrett** [comment]
Thanks! (:
